development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: spree_app_development

test:
  adapter: postgresql
  host: localhost
  username: postgres
  database: spree_app_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
